### ISSUE TITLE
Date not parsed properly

### ISSUE THREAD

**Issue by bayerj** [bjonnh/PyOrgMode#10]
Loading an org file of mine throws this error: 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bayerj/devel/third-party/PyOrgMode/PyOrgMode.py", line 487, in load_from_file
    current = plugin.treat(current,line)
  File "/Users/bayerj/devel/third-party/PyOrgMode/PyOrgMode.py", line 135, in treat
    return self._treat(current,line.lstrip(" \t"))
  File "/Users/bayerj/devel/third-party/PyOrgMode/PyOrgMode.py", line 240, in _treat
    self._append(current,self.Element(scheduled, deadline,closed))
  File "/Users/bayerj/devel/third-party/PyOrgMode/PyOrgMode.py", line 257, in __init__
    self.scheduled = OrgDate(scheduled)
  File "/Users/bayerj/devel/third-party/PyOrgMode/PyOrgMode.py", line 49, in **init**
    self.set_value(value)
  File "/Users/bayerj/devel/third-party/PyOrgMode/PyOrgMode.py", line 83, in set_value
    self.value = time.strptime(value,"%H:%M")
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/_strptime.py", line 454, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2011-07-27 Wed 19:00 -1w +1w' does not match format '%H:%M'

**Comment by bjonnh** [comment]
@bayerj I guess I can close that issue? If you think PyOrgMode is still affected by the bug, can you send me a minimal failing example?
