### ISSUE TITLE
some tests not passing

### ISSUE THREAD

**Issue by pascalfleury** [bjonnh/PyOrgMode#16]
I'm trying to use this module, and ran the tests. Unfortunately, two of them seem to fail. Am I missing some modules at all ?

$ python ./test_clock.py
======================================================================
ERROR: test_duration_format (__main__.TestClockElement)
Durations are formatted identically to org-mode
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_clock.py", line 15, in test_duration_format
    formatted_str = orgdate_element.get_value()
  File "/home/fleury/TEMP/PyOrgMode/PyOrgMode.py", line 187, in get_value
    '{start}{date}{repeat}{end}'.format(**fmt_dict), self.value)
AttributeError: OrgDate instance has no attribute 'value'

----------------------------------------------------------------------

$ python ./test.py
======================================================================
ERROR: test_test_org (__main__.TestExampleOrgFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test.py", line 26, in test_test_org
    test.save_to_file("output.org")
  File "/home/fleury/TEMP/PyOrgMode/PyOrgMode.py", line 747, in save_to_file
    output.write(str(node))
  File "/home/fleury/TEMP/PyOrgMode/PyOrgMode.py", line 260, in __str__
    return self.output()
  File "/home/fleury/TEMP/PyOrgMode/PyOrgMode.py", line 253, in output
    return self.indent+self._output()
  File "/home/fleury/TEMP/PyOrgMode/PyOrgMode.py", line 531, in _output
    output = output + element.__str__()
  File "/home/fleury/TEMP/PyOrgMode/PyOrgMode.py", line 260, in __str__
    return self.output()
  File "/home/fleury/TEMP/PyOrgMode/PyOrgMode.py", line 253, in output
    return self.indent+self._output()
  File "/home/fleury/TEMP/PyOrgMode/PyOrgMode.py", line 531, in _output
    output = output + element.__str__()
  File "/home/fleury/TEMP/PyOrgMode/PyOrgMode.py", line 260, in __str__
    return self.output()
  File "/home/fleury/TEMP/PyOrgMode/PyOrgMode.py", line 253, in output
    return self.indent+self._output()
  File "/home/fleury/TEMP/PyOrgMode/PyOrgMode.py", line 531, in _output
    output = output + element.__str__()
  File "/home/fleury/TEMP/PyOrgMode/PyOrgMode.py", line 260, in __str__
    return self.output()
  File "/home/fleury/TEMP/PyOrgMode/PyOrgMode.py", line 253, in output
    return self.indent+self._output()
  File "/home/fleury/TEMP/PyOrgMode/PyOrgMode.py", line 355, in _output
    output = output + "SCHEDULED: "+self.scheduled.get_value()+" "
  File "/home/fleury/TEMP/PyOrgMode/PyOrgMode.py", line 187, in get_value
    '{start}{date}{repeat}{end}'.format(**fmt_dict), self.value)
AttributeError: OrgDate instance has no attribute 'value'

----------------------------------------------------------------------

**Comment by bjonnh** [comment]
Sorry, I answer 2 years later, but all tests are ok now. But you need a fr_FR.utf8 locale to get test.py to pass… You can change the test.org file to a file not in French if you don't want to add the locale.
